issuer: http://dex-entra-telemark:5556/dex
storage:
  type: sqlite3
  config:
    file: /tmp/dex-telemark.db

web:
  http: 0.0.0.0:5556

oauth2:
  skipApprovalScreen: true

staticClients:
  - id: test-app
    name: Keycloak broker (external → entra-telemark)
    secret: test-secret
    redirectURIs:
      - http://keycloak:8080/realms/external/broker/entra-telemark/endpoint
      - http://localhost:8890/realms/external/broker/entra-telemark/endpoint

enablePasswordDB: true
staticPasswords:
  - email: alice.basic@example.com
    username: alice.basic
    userID: 11111111-1111-1111-1111-111111111111
    hash: $2b$10$pECRn7RvUKar9qQjpPUvGO8ZNuK5xezvXZOnX6TaD.SddrZwsMZBK
  - email: jon.basic@example.com
    username: jon.basic
    userID: 22222222-2222-2222-2222-222222222222
    hash: $2b$10$pECRn7RvUKar9qQjpPUvGO8ZNuK5xezvXZOnX6TaD.SddrZwsMZBK
