issuer: http://dex-entra-rogaland:5556/dex
storage:
    type: sqlite3
    config:
        file: /tmp/dex-rogaland.db

web:
    http: 0.0.0.0:5556

oauth2:
    skipApprovalScreen: true

staticClients:
    -   id: test-app
        name: Keycloak broker (external → entra-rogaland)
        secret: test-secret
        redirectURIs:
            - http://keycloak:8080/realms/external/broker/entra-rogaland/endpoint
            - http://localhost:8890/realms/external/broker/entra-rogaland/endpoint

enablePasswordDB: true
staticPasswords:
    -   email: alice.basic@rogaland.no
        username: alice.basic
        userID: 11111111-1111-1111-1111-111111111111
        hash: $2b$10$pECRn7RvUKar9qQjpPUvGO8ZNuK5xezvXZOnX6TaD.SddrZwsMZBK # password = password
    -   email: jon.basic@rogaland.no
        username: jon.basic
        userID: 22222222-2222-2222-2222-222222222222
        hash: $2b$10$pECRn7RvUKar9qQjpPUvGO8ZNuK5xezvXZOnX6TaD.SddrZwsMZBK # password = password
