apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: flais-keycloak-demo
  labels:
    app.kubernetes.io/name: flais-keycloak-demo
    app.kubernetes.io/component: flais-keycloak-demo
    app.kubernetes.io/instance: flais-keycloak-demo
    app.kubernetes.io/part-of: flais-keycloak-demo
    fintlabs.no/team: flais
    observability.fintlabs.no/loki: "true"
spec:
  port: 80
  image: ghcr.io/fintlabs/flais-keycloak-demo
  imagePullPolicy: Always
  replicas: 1
  resources:
    limits:
      memory: "100Mi"
      cpu: "50m"
    requests:
      memory: "100Mi"
      cpu: "50m"
