# rogaland.yaml
# https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: "Entra Rogaland"
  labels:
    blueprints.goauthentik.io/instantiate: "true"

entries:
  - model: authentik_blueprints.metaapplyblueprint
    attrs:
      identifiers:
        path: custom/scopes.yaml

  - model: authentik_core.group
    state: present
    identifiers:
      name: "entra-rogaland-users"

  - model: authentik_core.user
    state: present
    identifiers:
      username: "8b08335d-e716-4d45-8d40-f75aa7884083"
    attrs:
      name: "Alice Basic"
      email: "alice.basic@rogaland.no"
      is_active: true
      password: "password"
      groups:
        - !Find [ authentik_core.group, [ name, "entra-rogaland-users" ] ]
      attributes:
        oid: "8b08335d-e716-4d45-8d40-f75aa7884083"
        given_name: "Alice"
        family_name: "Basic"
        roles:
          - "read"
          - "write"
          - "admin"

  - model: authentik_core.user
    state: present
    identifiers:
      username: "84ad338c-b778-43f2-9636-1e2dda3d9f08"
    attrs:
      name: "Jon Basic"
      email: "jon.basic@rogaland.no"
      is_active: true
      password: "password"
      groups:
        - !Find [ authentik_core.group, [ name, "entra-rogaland-users" ] ]
      attributes:
        oid: "84ad338c-b778-43f2-9636-1e2dda3d9f08"
        given_name: "Jon"
        family_name: "Basic"
        roles:
          - "read"
          - "write"
          - "admin"

  - model: authentik_core.user
    state: present
    identifiers:
      username: "dc759da2-c412-47ba-b455-982d3f437ac5"
    attrs:
      name: "Qlik Basic"
      email: "qlik.basic@rogaland.no"
      is_active: true
      password: "password"
      groups:
        - !Find [ authentik_core.group, [ name, "entra-rogaland-users" ] ]
      attributes:
        oid: "dc759da2-c412-47ba-b455-982d3f437ac5"
        given_name: "Qlik"
        family_name: "Basic"
        roles:
          - "read"
          - "https://role-catalog.vigoiks.no/vigo/qlik/qliksense/fk-fagopplaring"
          - "https://role-catalog.vigoiks.no/vigo/qlik/qliksense/fk-dokumentasjon"
          - "1_https://role-catalog.vigoiks.no/vigo/qlik/qliksense/fk-dokumentasjon"

  - model: authentik_providers_oauth2.oauth2provider
    state: present
    identifiers:
      name: "entra-rogaland-provider"
    attrs:
      client_type: "confidential"
      client_id: "entra-rogaland"
      client_secret: "test-secret"

      grant_types:
        - authorization_code
        - refresh_token

      signing_key:
        !Find [
          authentik_crypto.certificatekeypair,
          [ name, "authentik Self-signed Certificate" ],
        ]
      authorization_flow:
        !Find [
          authentik_flows.flow,
          [ slug, "default-provider-authorization-implicit-consent" ],
        ]
      invalidation_flow:
        !Find [
          authentik_flows.flow,
          [ slug, "default-provider-invalidation-flow" ],
        ]
      property_mappings:
        - !Find [
          authentik_providers_oauth2.scopemapping,
          [ name, "authentik default OAuth Mapping: OpenID 'openid'" ],
        ]
        - !Find [
          authentik_providers_oauth2.scopemapping,
          [ name, "authentik default OAuth Mapping: OpenID 'profile'" ],
        ]
        - !Find [
          authentik_providers_oauth2.scopemapping,
          [ name, "authentik default OAuth Mapping: OpenID 'email'" ],
        ]
        - !Find [
          authentik_providers_oauth2.scopemapping,
          [ name, "authentik default OAuth Mapping: OpenID 'offline_access'" ],
        ]
        - !Find [
          authentik_providers_oauth2.scopemapping,
          [ name, "Custom OAuth Mapping: Entra OID" ],
        ]
        - !Find [
          authentik_providers_oauth2.scopemapping,
          [ name, "Custom OAuth Mapping: Entra Name" ],
        ]
        - !Find [
          authentik_providers_oauth2.scopemapping,
          [ name, "Custom OAuth Mapping: Entra Roles" ],
        ]
      redirect_uris:
        - url: "^http://localhost:[0-9]{1,5}/realms/external/broker/entra-rogaland/endpoint$"
          matching_mode: regex
          redirect_uri_type: authorization

        - url: "^http://127\\.0\\.0\\.1:[0-9]{1,5}/realms/external/broker/entra-rogaland/endpoint$"
          matching_mode: regex
          redirect_uri_type: authorization

  - model: authentik_core.application
    state: present
    identifiers:
      slug: "entra-rogaland-app"
    attrs:
      name: "Entra Rogaland"
      provider:
        !Find [
          authentik_providers_oauth2.oauth2provider,
          [ name, "entra-rogaland-provider" ],
        ]
      policy_engine_mode: "any"

  - model: authentik_policies.policybinding
    state: present
    identifiers:
      target: !Find [ authentik_core.application, [ slug, "entra-rogaland-app" ] ]
      order: 0
    attrs:
      group: !Find [ authentik_core.group, [ name, "entra-rogaland-users" ] ]
