name: Extract version from libs.versions.toml

on:
  workflow_call:
    inputs:
      libs_versions_path:
        description: "Path to libs.versions.toml"
        required: true
        type: string
      lib_name:
        description: "Library name to extract version for"
        required: true
        type: string
    outputs:
      version:
        description: "Extracted version from libs.versions.toml"
        value: ${{ jobs.extract.outputs.version }}

jobs:
  extract:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.parse.outputs.version }}
    steps:
      - uses: actions/checkout@v5

      - id: parse
        name: Read version from TOML
        env:
          LIBS_VERSIONS_PATH: ${{ inputs.libs_versions_path }}
        run: |
          python - <<'PY'
          import os, tomllib
          path = os.environ.get("LIBS_VERSIONS_PATH", "libs.versions.toml")
          with open(path, "rb") as f:
              data = tomllib.load(f)
          v = data["versions"]["${{ inputs.lib_name }}"]
          with open(os.environ["GITHUB_OUTPUT"], "a") as out:
              out.write(f"version={v}\n")
          PY

      - name: Show extracted version
        run: echo "Extracted VERSION=${{ steps.parse.outputs.version }}"
