name: Flais Keycloak Apps - Build, publish and deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "alpha"
        type: choice
        options:
          - alpha

permissions:
  actions: read
  id-token: write
  contents: write
  packages: write

jobs:
  build-publish-flais-keycloak-demo:
    name: Build and Publish Flais Keycloak Demo - ${{ inputs.environment }}
    uses: ./.github/workflows/.build-publish-docker.yaml
    secrets: inherit
    with:
      environment: prod
      image_name: ${{ github.repository }}-demo
      context: ./demo

  deploy-flais-keycloak-demo:
    name: Deploy Flais Keycloak Demo - ${{ inputs.environment }}
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/.cluster-deploy.yaml
    needs: build-publish-flais-keycloak-demo
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      image-tags: ${{ needs.build-publish-flais-keycloak-demo.outputs.image-tags }}
