name: Flais Keycloak - Build, publish and release

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - prod

permissions:
  contents: write
  packages: write

jobs:
  build-publish:
    name: Build and Publish Flais Keycloak
    uses: ./.github/workflows/.build-publish-docker.yaml
    secrets: inherit
    with:
      image_name: ${{ github.repository }}
      context: ./keycloak
      environment: ${{ inputs.environment }}

  publish-chart:
    name: Publish Flais Keycloak Helm Chart
    needs: build-publish
    uses: ./.github/workflows/.chart-publish.yaml
    with:
      image-tags: ${{ needs.build-publish.outputs.image-tags }}
      chart-name: ${{ github.event.repository.name }}
    secrets: inherit

  create-release:
    name: Create release for Flais Keycloak
    if: inputs.environment == 'prod' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/.create-release.yaml
    needs:
      - build-publish
      - publish-chart
    secrets: inherit
    with:
      image-tags: ${{ needs.build-publish.outputs.image-tags }}
