name: Build, publish and release

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - prod
  push:
    branches:
      - prod

permissions:
  contents: write
  packages: write

jobs:
  build-publish-test:
    name: Build and Publish App - Test
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && inputs.environment == 'test')
    uses: ./.github/workflows/.build-publish-docker.yaml
    secrets: inherit
    with:
      environment: test

  build-publish-prod:
    name: Build and Publish App - Prod
    if: github.ref == 'refs/heads/prod' || (github.event_name == 'workflow_dispatch' && inputs.environment == 'prod')
    uses: ./.github/workflows/.build-publish-docker.yaml
    secrets: inherit
    with:
      environment: prod

  publish-chart:
    name: Publish Helm Chart ${{ github.event.repository.name }}
    if: github.ref == 'refs/heads/prod' || (github.event_name == 'workflow_dispatch' && inputs.environment == 'prod')
    needs: build-publish-prod
    uses: ./.github/workflows/.chart-publish.yaml
    with:
      image-tags: ${{ needs.build-publish-prod.outputs.image-tags }}
      chart-name: ${{ github.event.repository.name }}
    secrets: inherit

  create-release:
    name: Create release for version ${{ needs.build-publish-prod.outputs.image-tags }}
    if: github.ref == 'refs/heads/prod'
    uses: ./.github/workflows/.create-release.yaml
    needs:
      - build-publish-prod
      - publish-chart
    secrets: inherit
    with:
      image-tags: ${{ needs.build-publish-prod.outputs.image-tags }}
